//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxSRL.SMS.SMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMS.wmgwSoap")]
    public interface wmgwSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse MongateCsSpSendSmsNew(AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse> MongateCsSpSendSmsNewAsync(AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateCsGetSmsExExResponse MongateCsGetSmsExEx(AxSRL.SMS.SMS.MongateCsGetSmsExExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetSmsExExResponse> MongateCsGetSmsExExAsync(AxSRL.SMS.SMS.MongateCsGetSmsExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse MongateCsGetStatusReportExEx(AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse> MongateCsGetStatusReportExExAsync(AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetStatusReport", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateGetStatusReportResponse MongateGetStatusReport(AxSRL.SMS.SMS.MongateGetStatusReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetStatusReport", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetStatusReportResponse> MongateGetStatusReportAsync(AxSRL.SMS.SMS.MongateGetStatusReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateQueryBalance", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateQueryBalanceResponse MongateQueryBalance(AxSRL.SMS.SMS.MongateQueryBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateQueryBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateQueryBalanceResponse> MongateQueryBalanceAsync(AxSRL.SMS.SMS.MongateQueryBalanceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetDeliver", ReplyAction="*")]
        AxSRL.SMS.SMS.MongateGetDeliverResponse MongateGetDeliver(AxSRL.SMS.SMS.MongateGetDeliverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetDeliver", ReplyAction="*")]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetDeliverResponse> MongateGetDeliverAsync(AxSRL.SMS.SMS.MongateGetDeliverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNew", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequestBody Body;
        
        public MongateCsSpSendSmsNewRequest() {
        }
        
        public MongateCsSpSendSmsNewRequest(AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pszMobis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pszMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iMobiCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pszSubPort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SvrType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MsgId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Attime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Validtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int RptFlag;
        
        public MongateCsSpSendSmsNewRequestBody() {
        }
        
        public MongateCsSpSendSmsNewRequestBody(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            this.userId = userId;
            this.password = password;
            this.pszMobis = pszMobis;
            this.pszMsg = pszMsg;
            this.iMobiCount = iMobiCount;
            this.pszSubPort = pszSubPort;
            this.SvrType = SvrType;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
            this.Param4 = Param4;
            this.MsgId = MsgId;
            this.ModuleId = ModuleId;
            this.Attime = Attime;
            this.Validtime = Validtime;
            this.RptFlag = RptFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponseBody Body;
        
        public MongateCsSpSendSmsNewResponse() {
        }
        
        public MongateCsSpSendSmsNewResponse(AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateCsSpSendSmsNewResult;
        
        public MongateCsSpSendSmsNewResponseBody() {
        }
        
        public MongateCsSpSendSmsNewResponseBody(string MongateCsSpSendSmsNewResult) {
            this.MongateCsSpSendSmsNewResult = MongateCsSpSendSmsNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExEx", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsGetSmsExExRequestBody Body;
        
        public MongateCsGetSmsExExRequest() {
        }
        
        public MongateCsGetSmsExExRequest(AxSRL.SMS.SMS.MongateCsGetSmsExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetSmsExExRequestBody() {
        }
        
        public MongateCsGetSmsExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsGetSmsExExResponseBody Body;
        
        public MongateCsGetSmsExExResponse() {
        }
        
        public MongateCsGetSmsExExResponse(AxSRL.SMS.SMS.MongateCsGetSmsExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AxSRL.SMS.SMS.ArrayOfString MongateCsGetSmsExExResult;
        
        public MongateCsGetSmsExExResponseBody() {
        }
        
        public MongateCsGetSmsExExResponseBody(AxSRL.SMS.SMS.ArrayOfString MongateCsGetSmsExExResult) {
            this.MongateCsGetSmsExExResult = MongateCsGetSmsExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExEx", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequestBody Body;
        
        public MongateCsGetStatusReportExExRequest() {
        }
        
        public MongateCsGetStatusReportExExRequest(AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetStatusReportExExRequestBody() {
        }
        
        public MongateCsGetStatusReportExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponseBody Body;
        
        public MongateCsGetStatusReportExExResponse() {
        }
        
        public MongateCsGetStatusReportExExResponse(AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AxSRL.SMS.SMS.ArrayOfString MongateCsGetStatusReportExExResult;
        
        public MongateCsGetStatusReportExExResponseBody() {
        }
        
        public MongateCsGetStatusReportExExResponseBody(AxSRL.SMS.SMS.ArrayOfString MongateCsGetStatusReportExExResult) {
            this.MongateCsGetStatusReportExExResult = MongateCsGetStatusReportExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetStatusReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetStatusReport", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateGetStatusReportRequestBody Body;
        
        public MongateGetStatusReportRequest() {
        }
        
        public MongateGetStatusReportRequest(AxSRL.SMS.SMS.MongateGetStatusReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetStatusReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgId;
        
        public MongateGetStatusReportRequestBody() {
        }
        
        public MongateGetStatusReportRequestBody(string userId, string password, string MsgId) {
            this.userId = userId;
            this.password = password;
            this.MsgId = MsgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetStatusReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetStatusReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateGetStatusReportResponseBody Body;
        
        public MongateGetStatusReportResponse() {
        }
        
        public MongateGetStatusReportResponse(AxSRL.SMS.SMS.MongateGetStatusReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetStatusReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AxSRL.SMS.SMS.ArrayOfString MongateGetStatusReportResult;
        
        public MongateGetStatusReportResponseBody() {
        }
        
        public MongateGetStatusReportResponseBody(AxSRL.SMS.SMS.ArrayOfString MongateGetStatusReportResult) {
            this.MongateGetStatusReportResult = MongateGetStatusReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalance", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateQueryBalanceRequestBody Body;
        
        public MongateQueryBalanceRequest() {
        }
        
        public MongateQueryBalanceRequest(AxSRL.SMS.SMS.MongateQueryBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateQueryBalanceRequestBody() {
        }
        
        public MongateQueryBalanceRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateQueryBalanceResponseBody Body;
        
        public MongateQueryBalanceResponse() {
        }
        
        public MongateQueryBalanceResponse(AxSRL.SMS.SMS.MongateQueryBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MongateQueryBalanceResult;
        
        public MongateQueryBalanceResponseBody() {
        }
        
        public MongateQueryBalanceResponseBody(int MongateQueryBalanceResult) {
            this.MongateQueryBalanceResult = MongateQueryBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliver", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateGetDeliverRequestBody Body;
        
        public MongateGetDeliverRequest() {
        }
        
        public MongateGetDeliverRequest(AxSRL.SMS.SMS.MongateGetDeliverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iReqType;
        
        public MongateGetDeliverRequestBody() {
        }
        
        public MongateGetDeliverRequestBody(string userId, string password, int iReqType) {
            this.userId = userId;
            this.password = password;
            this.iReqType = iReqType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliverResponse", Namespace="http://tempuri.org/", Order=0)]
        public AxSRL.SMS.SMS.MongateGetDeliverResponseBody Body;
        
        public MongateGetDeliverResponse() {
        }
        
        public MongateGetDeliverResponse(AxSRL.SMS.SMS.MongateGetDeliverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AxSRL.SMS.SMS.ArrayOfString MongateGetDeliverResult;
        
        public MongateGetDeliverResponseBody() {
        }
        
        public MongateGetDeliverResponseBody(AxSRL.SMS.SMS.ArrayOfString MongateGetDeliverResult) {
            this.MongateGetDeliverResult = MongateGetDeliverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wmgwSoapChannel : AxSRL.SMS.SMS.wmgwSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wmgwSoapClient : System.ServiceModel.ClientBase<AxSRL.SMS.SMS.wmgwSoap>, AxSRL.SMS.SMS.wmgwSoap {
        
        public wmgwSoapClient() {
        }
        
        public wmgwSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse AxSRL.SMS.SMS.wmgwSoap.MongateCsSpSendSmsNew(AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest request) {
            return base.Channel.MongateCsSpSendSmsNew(request);
        }
        
        public string MongateCsSpSendSmsNew(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest inValue = new AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            inValue.Body.SvrType = SvrType;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            inValue.Body.Param4 = Param4;
            inValue.Body.MsgId = MsgId;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.Attime = Attime;
            inValue.Body.Validtime = Validtime;
            inValue.Body.RptFlag = RptFlag;
            AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsSpSendSmsNew(inValue);
            return retVal.Body.MongateCsSpSendSmsNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse> AxSRL.SMS.SMS.wmgwSoap.MongateCsSpSendSmsNewAsync(AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest request) {
            return base.Channel.MongateCsSpSendSmsNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsSpSendSmsNewResponse> MongateCsSpSendSmsNewAsync(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest inValue = new AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsSpSendSmsNewRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            inValue.Body.SvrType = SvrType;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            inValue.Body.Param4 = Param4;
            inValue.Body.MsgId = MsgId;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.Attime = Attime;
            inValue.Body.Validtime = Validtime;
            inValue.Body.RptFlag = RptFlag;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsSpSendSmsNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateCsGetSmsExExResponse AxSRL.SMS.SMS.wmgwSoap.MongateCsGetSmsExEx(AxSRL.SMS.SMS.MongateCsGetSmsExExRequest request) {
            return base.Channel.MongateCsGetSmsExEx(request);
        }
        
        public AxSRL.SMS.SMS.ArrayOfString MongateCsGetSmsExEx(string userId, string password) {
            AxSRL.SMS.SMS.MongateCsGetSmsExExRequest inValue = new AxSRL.SMS.SMS.MongateCsGetSmsExExRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsGetSmsExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            AxSRL.SMS.SMS.MongateCsGetSmsExExResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsGetSmsExEx(inValue);
            return retVal.Body.MongateCsGetSmsExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetSmsExExResponse> AxSRL.SMS.SMS.wmgwSoap.MongateCsGetSmsExExAsync(AxSRL.SMS.SMS.MongateCsGetSmsExExRequest request) {
            return base.Channel.MongateCsGetSmsExExAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetSmsExExResponse> MongateCsGetSmsExExAsync(string userId, string password) {
            AxSRL.SMS.SMS.MongateCsGetSmsExExRequest inValue = new AxSRL.SMS.SMS.MongateCsGetSmsExExRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsGetSmsExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsGetSmsExExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse AxSRL.SMS.SMS.wmgwSoap.MongateCsGetStatusReportExEx(AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest request) {
            return base.Channel.MongateCsGetStatusReportExEx(request);
        }
        
        public AxSRL.SMS.SMS.ArrayOfString MongateCsGetStatusReportExEx(string userId, string password) {
            AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest inValue = new AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsGetStatusReportExEx(inValue);
            return retVal.Body.MongateCsGetStatusReportExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse> AxSRL.SMS.SMS.wmgwSoap.MongateCsGetStatusReportExExAsync(AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest request) {
            return base.Channel.MongateCsGetStatusReportExExAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateCsGetStatusReportExExResponse> MongateCsGetStatusReportExExAsync(string userId, string password) {
            AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest inValue = new AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateCsGetStatusReportExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateCsGetStatusReportExExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateGetStatusReportResponse AxSRL.SMS.SMS.wmgwSoap.MongateGetStatusReport(AxSRL.SMS.SMS.MongateGetStatusReportRequest request) {
            return base.Channel.MongateGetStatusReport(request);
        }
        
        public AxSRL.SMS.SMS.ArrayOfString MongateGetStatusReport(string userId, string password, string MsgId) {
            AxSRL.SMS.SMS.MongateGetStatusReportRequest inValue = new AxSRL.SMS.SMS.MongateGetStatusReportRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateGetStatusReportRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.MsgId = MsgId;
            AxSRL.SMS.SMS.MongateGetStatusReportResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateGetStatusReport(inValue);
            return retVal.Body.MongateGetStatusReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetStatusReportResponse> AxSRL.SMS.SMS.wmgwSoap.MongateGetStatusReportAsync(AxSRL.SMS.SMS.MongateGetStatusReportRequest request) {
            return base.Channel.MongateGetStatusReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetStatusReportResponse> MongateGetStatusReportAsync(string userId, string password, string MsgId) {
            AxSRL.SMS.SMS.MongateGetStatusReportRequest inValue = new AxSRL.SMS.SMS.MongateGetStatusReportRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateGetStatusReportRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.MsgId = MsgId;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateGetStatusReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateQueryBalanceResponse AxSRL.SMS.SMS.wmgwSoap.MongateQueryBalance(AxSRL.SMS.SMS.MongateQueryBalanceRequest request) {
            return base.Channel.MongateQueryBalance(request);
        }
        
        public int MongateQueryBalance(string userId, string password) {
            AxSRL.SMS.SMS.MongateQueryBalanceRequest inValue = new AxSRL.SMS.SMS.MongateQueryBalanceRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateQueryBalanceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            AxSRL.SMS.SMS.MongateQueryBalanceResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateQueryBalance(inValue);
            return retVal.Body.MongateQueryBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateQueryBalanceResponse> AxSRL.SMS.SMS.wmgwSoap.MongateQueryBalanceAsync(AxSRL.SMS.SMS.MongateQueryBalanceRequest request) {
            return base.Channel.MongateQueryBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateQueryBalanceResponse> MongateQueryBalanceAsync(string userId, string password) {
            AxSRL.SMS.SMS.MongateQueryBalanceRequest inValue = new AxSRL.SMS.SMS.MongateQueryBalanceRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateQueryBalanceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateQueryBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AxSRL.SMS.SMS.MongateGetDeliverResponse AxSRL.SMS.SMS.wmgwSoap.MongateGetDeliver(AxSRL.SMS.SMS.MongateGetDeliverRequest request) {
            return base.Channel.MongateGetDeliver(request);
        }
        
        public AxSRL.SMS.SMS.ArrayOfString MongateGetDeliver(string userId, string password, int iReqType) {
            AxSRL.SMS.SMS.MongateGetDeliverRequest inValue = new AxSRL.SMS.SMS.MongateGetDeliverRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateGetDeliverRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.iReqType = iReqType;
            AxSRL.SMS.SMS.MongateGetDeliverResponse retVal = ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateGetDeliver(inValue);
            return retVal.Body.MongateGetDeliverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetDeliverResponse> AxSRL.SMS.SMS.wmgwSoap.MongateGetDeliverAsync(AxSRL.SMS.SMS.MongateGetDeliverRequest request) {
            return base.Channel.MongateGetDeliverAsync(request);
        }
        
        public System.Threading.Tasks.Task<AxSRL.SMS.SMS.MongateGetDeliverResponse> MongateGetDeliverAsync(string userId, string password, int iReqType) {
            AxSRL.SMS.SMS.MongateGetDeliverRequest inValue = new AxSRL.SMS.SMS.MongateGetDeliverRequest();
            inValue.Body = new AxSRL.SMS.SMS.MongateGetDeliverRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.iReqType = iReqType;
            return ((AxSRL.SMS.SMS.wmgwSoap)(this)).MongateGetDeliverAsync(inValue);
        }
    }
}
