//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ax.Server.WcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangeZTW", ReplyAction="http://tempuri.org/IService/ChangeZTWResponse")]
        bool ChangeZTW(System.Collections.Generic.Dictionary<string, bool> dic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangeZTW", ReplyAction="http://tempuri.org/IService/ChangeZTWResponse")]
        System.Threading.Tasks.Task<bool> ChangeZTWAsync(System.Collections.Generic.Dictionary<string, bool> dic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Ax.Server.WcfService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Ax.Server.WcfService.IService>, Ax.Server.WcfService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChangeZTW(System.Collections.Generic.Dictionary<string, bool> dic) {
            return base.Channel.ChangeZTW(dic);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeZTWAsync(System.Collections.Generic.Dictionary<string, bool> dic) {
            return base.Channel.ChangeZTWAsync(dic);
        }
    }
}
